theme: jekyll-theme-cayman
name: s2s-ai-challenge
title: Challenge to improve Sub-seasonal to Seasonal Predictions using Artificial Intelligence
author:
  fullname: Aaron Spring
  mail: aaron.spring@mpimet.mpg.de
  github: @aaronspring
  twitter: @realaaronspring
language: en
date_format: '%Y-%m-%d'
