name: CI
on:
  push:
    branches: [ gh-pages ]
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch:

jobs:
  keep_leaderboard_updated:
    runs-on: ubuntu-latest
    name: Keep leaderboard updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update leaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/leaderboard.html
        file_in_repo: leaderboard.html

  keep_subleaderboard_tp_NH updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard tp NH updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_tp_northern_extratropics.html
        file_in_repo: subleaderboard_tp_northern_extratropics.html

  keep_subleaderboard_tp_T_updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard tp T updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_tp_tropics.html
        file_in_repo: subleaderboard_tp_tropics.html

  keep_subleaderboard_tp_SH_updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard tp SH updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_tp_southern_extratropics.html
        file_in_repo: subleaderboard_tp_southern_extratropics.html

  keep_subleaderboard_2t_NH updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard 2t NH updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_2t_northern_extratropics.html
        file_in_repo: subleaderboard_2t_northern_extratropics.html

  keep_subleaderboard_2t_T_updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard 2t T updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_2t_tropics.html
        file_in_repo: subleaderboard_2t_tropics.html

  keep_subleaderboard_2t_SH_updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard 2t SH updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_2t_southern_extratropics.html
        file_in_repo: subleaderboard_2t_southern_extratropics.html
