name: CI
on:
  push:
    branches: [ gh-pages ]
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch:

jobs:
  keep_leaderboard_updated:
    runs-on: ubuntu-latest
    name: Keep leaderboard updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update leaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/leaderboard.html
        file_in_repo: leaderboard.html
  keep_subleaderboard_updated:
    runs-on: ubuntu-latest
    name: Keep subleaderboard updated
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update subleaderboard
      id: update_file
      uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
      with:
        url: https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/raw/master/leaderboards/subleaderboard_2t_northern_extratropics.html
        file_in_repo: subleaderboard_2t_northern_extratropics.html
